### PR TITLE
Provide the configuration for 7 banks.

### PR DESCRIPTION
**Pull request by bartfeenstra**
This introduces banks' known configuration, based on https://github.com/tuutti/tupas/tree/8.x-1.x/config/install.

### CODE REVIEW

**Comment by tuutti** [comment]
I think receiverId and receiverKey should be overridable (either via constructor or setter method) as it doesn't make much sense to have value objects just for test credentials.

**Comment by bartfeenstra** [comment]
What about I make these base classes without those two values, and I subclass them as `*TestBank`. It's a bit of boilerplate, but it can't really break and makes using these banks in development environments a breeze.

**Comment by tuutti** [comment]
Actually everything except actionUrl and bankNumber should be something that can be changed (providing a default value is fine). 

I'm also okay with subclassing them as *TestBank.

**Comment by bartfeenstra** [comment]
Thanks for the feedback :) I'll take a look at this again tomorrow.

**Comment by bartfeenstra** [comment]
To ensure these banks are indeed immutable, see https://github.com/tuutti/php-tupas/pull/3.

**Comment by tuutti** [comment]
Merged. Thank you!

**Comment by bartfeenstra** [comment]
Yay! Thanks for the Alpha release :)

**Pull request merged**
